name: zawa

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  cwcGL:
    type: library.dynamic
    platform: macOS
    sources:
        - path: deps/cwcGL/src
          excludes:
            - "backends/"
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps/cwcGL/src]
    dependencies:
        - sdk: Cocoa.framework
  zawa:
    type: tool
    platform: macOS
    sources:
        - path: assets/
          type: folder
        - path: deps/
          type: folder
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: Makefile
          type: folder
        - path: project.yml
          type: folder
        - path: README.md
          type: folder
        - path: src/
    dependencies:
        - target: cwcGL
        - sdk: deps/ode/build/libode.dylib
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps/glm, $(PROJECT_DIR)/deps/ode/include, $(PROJECT_DIR)/deps/ode/build/include]
        LIBRARY_SEARCH_PATHS: [$(PROJECT_DIR)/deps/ode/build]
        OTHER_CFLAGS: ["-x objective-c++", -fobjc-arc]
