name: zawa

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  zawa:
    type: tool
    platform: macOS
    sources:
        - path: assets/
          type: folder
        - path: deps/
          excludes:
            - "glm/test/"
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: Makefile
          type: folder
        - path: project.yml
          type: folder
        - path: README.md
          type: folder
        - path: src/
    dependencies:
        - sdk: /opt/homebrew/lib/libSDL2.dylib
    settings:
        HEADER_SEARCH_PATHS: [/opt/homebrew/include, $(PROJECT_DIR)/build, $(PROJECT_DIR)/deps, $(PROJECT_DIR)/deps/glm]
        LIBRARY_SEARCH_PATHS: [/opt/homebrew/lib]
        OTHER_CFLAGS: ["-x objective-c++", -fobjc-arc]
